# encoding: UTF-8

defineDict = {}

defineDict['server_force'] = '1' ## 服务端强制断开
defineDict['client_close'] = '2' ## 客户端断开
defineDict['timeout'] = '3' ## 连接超时断开
defineDict['none'] = '0' ##
defineDict['NORMAL'] = '1' ## 正常退出
defineDict['TIMEOUT'] = '2' ## 超时退出
defineDict['FORCEOUT'] = '3' ## 强制踢出
defineDict['OTHERIN'] = '4' ## 同帐号登录踢出
defineDict['CLOSE'] = '0' ## 闭市
defineDict['INIT'] = '1' ## 初始化
defineDict['AUCTION_ORDERING'] = '2' ## 集合竞价申报
defineDict['AUCTION_MATCH'] = '3' ## 集合竞价撮合
defineDict['TRADING'] = '4' ## 连续交易
defineDict['PAUSE'] = '5' ## 暂停
defineDict['CLOSING_DEAL'] = 'E' ## 收市处理
defineDict['BeforeFuse'] = 'B' ## 熔断前
defineDict['Fusing'] = 'T' ## 熔断中
defineDict['Fused'] = 'A' ## 已熔断
defineDict['future'] = '1' ## 中远期
defineDict['swap'] = '4' ## 掉期
defineDict['goods'] = '1' ## 实物交收
defineDict['cash'] = '2' ## 现金交割
defineDict['trade'] = '1' ## 可交易
defineDict['nottrade'] = '0' ## 不可交易
defineDict['open'] = '1' ## 开仓
defineDict['close'] = '2' ## 平仓
defineDict['forceclose'] = '3' ## 强制平仓
defineDict['normal'] = '0' ## 默认
defineDict['close_today'] = '1' ## 平今
defineDict['nodeal'] = 1 ## 未成交
defineDict['partdeal'] = 2 ## 部分成交
defineDict['alldeal'] = 3 ## 完全成交
defineDict['canceled'] = 6 ## 已撤单
defineDict['invalid'] = '122' ## 作废
defineDict['agreement_defineault'] = '0' ## 正常(默认类型)
defineDict['agreement_open'] = '1' ## 协议开仓
defineDict['agreement_close'] = '2' ## 协议平仓
defineDict['agreement_exchange'] = '3' ## 协议换手
defineDict['Success'] = '0' ## 成功
defineDict['InvalidLicense'] = '1' ## License非法
defineDict['InvalidIP'] = '2' ## IP非法
defineDict['NotEnabledLicense'] = '3' ## License未生效
defineDict['OverdueLicense'] = '4' ## License已失效
defineDict['ExceedMaxConnection'] = '5' ## 超过最大连接数限制
defineDict['checking'] = '0' ## 待审核
defineDict['checked'] = '1' ## 审核
defineDict['overrule'] = '2' ## 驳回
defineDict['openprice'] = '0' ## 开仓价
defineDict['positionprice'] = '1' ## 持仓价
