# encoding: UTF-8

defineDict = {}
typedefDict = {}

typedefDict['server_force'] = '1' ## 服务端强制断开
typedefDict['client_close'] = '2' ## 客户端断开
typedefDict['timeout'] = '3' ## 连接超时断开
typedefDict['none'] = '0' ## 
typedefDict['NORMAL'] = '1' ## 正常退出
typedefDict['TIMEOUT'] = '2' ## 超时退出
typedefDict['FORCEOUT'] = '3' ## 强制踢出
typedefDict['OTHERIN'] = '4' ## 同帐号登录踢出
typedefDict['CLOSE'] = '0' ## 闭市
typedefDict['INIT'] = '1' ## 初始化
typedefDict['AUCTION_ORDERING'] = '2' ## 集合竞价申报
typedefDict['AUCTION_MATCH'] = '3' ## 集合竞价撮合
typedefDict['TRADING'] = '4' ## 连续交易
typedefDict['PAUSE'] = '5' ## 暂停
typedefDict['CLOSING_DEAL'] = 'E' ## 收市处理
typedefDict['BeforeFuse'] = 'B' ## 熔断前
typedefDict['Fusing'] = 'T' ## 熔断中
typedefDict['Fused'] = 'A' ## 已熔断
typedefDict['future'] = '1' ## 中远期
typedefDict['swap'] = '4' ## 掉期
typedefDict['goods'] = '1' ## 实物交收
typedefDict['cash'] = '2' ## 现金交割
typedefDict['trade'] = '1' ## 可交易
typedefDict['nottrade'] = '0' ## 不可交易
typedefDict['open'] = '1' ## 开仓
typedefDict['close'] = '2' ## 平仓
typedefDict['forceclose'] = '3' ## 强制平仓
typedefDict['normal'] = '0' ## 默认
typedefDict['close_today'] = '1' ## 平今
typedefDict['nodeal'] = '1' ## 未成交
typedefDict['partdeal'] = '2' ## 部分成交
typedefDict['alldeal'] = '3' ## 完全成交
typedefDict['canceled'] = '6' ## 已撤单
typedefDict['invalid'] = '122' ## 作废
typedefDict['agreement_default'] = '0' ## 正常(默认类型)
typedefDict['agreement_open'] = '1' ## 协议开仓
typedefDict['agreement_close'] = '2' ## 协议平仓
typedefDict['agreement_exchange'] = '3' ## 协议换手
typedefDict['Success'] = '0' ## 成功
typedefDict['InvalidLicense'] = '1' ## License非法
typedefDict['InvalidIP'] = '2' ## IP非法
typedefDict['NotEnabledLicense'] = '3' ## License未生效
typedefDict['OverdueLicense'] = '4' ## License已失效
typedefDict['ExceedMaxConnection'] = '5' ## 超过最大连接数限制
typedefDict['checking'] = '0' ## 待审核
typedefDict['checked'] = '1' ## 审核
typedefDict['overrule'] = '2' ## 驳回
typedefDict['openprice'] = '0' ## 开仓价
typedefDict['positionprice'] = '1' ## 持仓价
